# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Jon Douglas
tagline:             'The rantings of a developer'
description:         'Various blog posts on things I think are neat or difficult to understand'
url:                 https://jon-douglas.com
baseurl:             
paginate:            5
github:              https://github.com/jondouglas


# About/contact
author:
  name:              Jon Douglas
  url:               https://twitter.com/_jondouglas
  email:             jondouglas18@gmail.com
  twitter:           _jondouglas
  twitterUrl:        https://twitter.com/_jondouglas
  github:            https://github.com/jondouglas/

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]